/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { NewUserRequest } from '../model/models';
import { Role } from '../model/models';
import { UserProjection } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminAPIServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param role 
     */
    createRole(role: Role, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param newUserRequest 
     */
    createUser(newUserRequest: NewUserRequest, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     */
    getUsers(extraHttpRequestParams?: any): Observable<Array<UserProjection>>;

    /**
     * 
     * 
     * @param id 
     * @param role 
     */
    updateRole(id: number, role: Role, extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param id 
     * @param userProjection 
     */
    updateUser(id: number, userProjection: UserProjection, extraHttpRequestParams?: any): Observable<object>;

}
