/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Permission } from '../model/models';
import { Role } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthorizationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    getAllPermissions(extraHttpRequestParams?: any): Observable<Array<Permission>>;

    /**
     * 
     * 
     * @param permissionId The ID of the permission to fetch
     */
    getPermission(permissionId: number, extraHttpRequestParams?: any): Observable<Permission>;

    /**
     * 
     * 
     * @param roleId 
     */
    getRole(roleId: number, extraHttpRequestParams?: any): Observable<Role>;

    /**
     * 
     * 
     * @param roleId 
     */
    getRolePermissions(roleId: number, extraHttpRequestParams?: any): Observable<Array<Permission>>;

    /**
     * 
     * 
     */
    getRoles(extraHttpRequestParams?: any): Observable<Array<Role>>;

}
