/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { LoginRequestDTO } from '../model/models';
import { LoginResponseDTO } from '../model/models';
import { RegistrationDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthenticationAPIServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param loginRequestDTO 
     */
    loginUserV1(loginRequestDTO: LoginRequestDTO, extraHttpRequestParams?: any): Observable<LoginResponseDTO>;

    /**
     * 
     * 
     */
    logout(extraHttpRequestParams?: any): Observable<object>;

    /**
     * 
     * 
     * @param registrationDTO 
     */
    registerUserV1(registrationDTO: RegistrationDTO, extraHttpRequestParams?: any): Observable<object>;

}
