/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { QuestionBankCategory } from '../model/models';
import { QuestionBankQuestion } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface QuestionBankServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param questionBankCategory 
     */
    addCategory(questionBankCategory: QuestionBankCategory, extraHttpRequestParams?: any): Observable<QuestionBankCategory>;

    /**
     * 
     * 
     * @param questionBankCategory 
     */
    addCategory1(questionBankCategory: QuestionBankCategory, extraHttpRequestParams?: any): Observable<QuestionBankCategory>;

    /**
     * 
     * 
     * @param questionBankQuestion 
     */
    addQuestion(questionBankQuestion: QuestionBankQuestion, extraHttpRequestParams?: any): Observable<QuestionBankQuestion>;

    /**
     * 
     * 
     * @param questionBankQuestion 
     */
    addQuestion1(questionBankQuestion: QuestionBankQuestion, extraHttpRequestParams?: any): Observable<QuestionBankQuestion>;

    /**
     * 
     * 
     */
    getCategories(extraHttpRequestParams?: any): Observable<Array<QuestionBankCategory>>;

    /**
     * 
     * 
     */
    getQuestions(extraHttpRequestParams?: any): Observable<Array<QuestionBankQuestion>>;

}
