/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { User } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UsersAPIServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param user 
     */
    deleteClientAvatar(user: User, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param user 
     */
    getClientAvatar(user: User, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
     * @param user 
     * @param file 
     */
    updateClientAvatar(user: User, file: Blob, extraHttpRequestParams?: any): Observable<Blob>;

}
