/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { User } from '../model/models';
import { UserProjection } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface UsersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    deleteClientAvatar(extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    getClient(extraHttpRequestParams?: any): Observable<UserProjection>;

    /**
     * 
     * 
     */
    getClientAvatar(extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
     * @param userId 
     */
    getUserByIdV1(userId: number, extraHttpRequestParams?: any): Observable<User>;

    /**
     * 
     * 
     * @param page 
     * @param size 
     */
    getUsersV1(page: number, size: number, extraHttpRequestParams?: any): Observable<Array<UserProjection>>;

    /**
     * 
     * 
     * @param file 
     */
    updateClientAvatar(file: Blob, extraHttpRequestParams?: any): Observable<Blob>;

}
