/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssignmentQuestionAnswer } from './assignment-question-answer';


export interface AssignmentQuestionRequest { 
    id?: number;
    question?: string;
    title?: string;
    questionType?: string;
    answers?: Array<AssignmentQuestionAnswer>;
    createdAt?: string;
    updatedAt?: string;
    keepAnswersOrdered?: boolean;
    assignmentId?: number;
    order?: number;
}

