/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssignmentQuestion } from './assignment-question';
import { CourseDetailsProjection } from './course-details-projection';


export interface AssignmentEditDetailsProjection { 
    id?: number;
    name?: string;
    description?: string;
    dueDate?: string;
    startDate?: string;
    course?: CourseDetailsProjection;
    maxAttempts?: number;
    timeLimitMinutes?: number;
    questions?: Array<AssignmentQuestion>;
}

