/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssignmentQuestionAnswerProjection } from './assignment-question-answer-projection';


export interface AssignmentQuestionProjection { 
    id?: number;
    title?: string;
    question?: string;
    createdAt?: string;
    updatedAt?: string;
    questionType?: string;
    keepAnswersOrdered?: boolean;
    order?: number;
    answers?: Array<AssignmentQuestionAnswerProjection>;
}

