/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssignmentQuestionProjection } from './assignment-question-projection';
import { CourseProjection } from './course-projection';


export interface AssignmentProjection { 
    id?: number;
    name?: string;
    description?: string;
    questions?: Array<AssignmentQuestionProjection>;
    course?: CourseProjection;
    maxAttempts?: number;
    timeLimitMinutes?: number;
    startDate?: string;
    dueDate?: string;
    createdAt?: string;
    updatedAt?: string;
}

