/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AssignmentQuestion } from './assignment-question';
import { Course } from './course';


export interface Assignment { 
    id?: number;
    name?: string;
    description?: string;
    startDate?: string;
    dueDate?: string;
    createdAt?: string;
    updatedAt?: string;
    questions?: Array<AssignmentQuestion>;
    course?: Course;
    maxAttempts?: number;
    timeLimitMinutes?: number;
}

