/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AttemptQuestionAnswerProjection } from './attempt-question-answer-projection';
import { AssignmentProjection } from './assignment-projection';
import { UserProjection } from './user-projection';


export interface AssignmentAttemptProjection { 
    id?: string;
    assignment?: AssignmentProjection;
    user?: UserProjection;
    status?: AssignmentAttemptProjection.StatusEnum;
    startedAt?: string;
    answers?: Array<AttemptQuestionAnswerProjection>;
    scorePercentage?: number;
    answersCorrect?: number;
}
export namespace AssignmentAttemptProjection {
    export type StatusEnum = 'IN_PROGRESS' | 'SUBMITTED';
    export const StatusEnum = {
        InProgress: 'IN_PROGRESS' as StatusEnum,
        Submitted: 'SUBMITTED' as StatusEnum
    };
}


