/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserProjection } from './user-projection';


export interface LoginResponseDTO { 
    accessToken?: string;
    user?: UserProjection;
}

