/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { QuestionBankCategory } from './question-bank-category';


export interface QuestionBankQuestion { 
    id?: number;
    questionName?: string;
    categories?: Array<QuestionBankCategory>;
}

