/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';
import { Permission } from './permission';


export interface User { 
    id?: number;
    authenticationProfileId?: number;
    firstName?: string;
    lastName?: string;
    username?: string;
    dateOfBirth?: string;
    roles?: Set<Role>;
    permissions?: Set<Permission>;
}

