spring:
  application:
    name: api
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5001/clms
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:changeme}
  cloud:
    aws:
      s3:
        endpoint: http://s3.localhost.localstack.cloud:4566
        region: us-east-1
      credentials:
        access-key: ${AWS_ACCESS_KEY:localstack}
        secret-key: ${AWS_SECRET_KEY:localstack}
      region:
        static: us-east-1
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jackson:
    serialization:
      fail-on-empty-beans: false

springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

clms:
  security:
    access-token:
      expiration-time: 86400000
      secret: ${ACCESS_TOKEN_SECRET:changeme}
  password:
    strength: 10

gemini-configuration:
  enabled: ${GEMINI_ENABLED:false}
  api-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent
  api-key: ${GEMINI_API_KEY:''}

question-generation-configuration:
  enabled: ${QUESTION_GENERATION_ENABLED:false}


