spring:
  application:
    name: clms-api
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: jdbc:postgresql://localhost:5001/clms
    username: admin
    password: changeme
  cloud:
    aws:
      s3:
        endpoint: http://s3.localhost.localstack.cloud:4566
        region: us-east-1
      credentials:
        access-key: localstack
        secret-key: localstack
      region:
        static: us-east-1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
clms:
  security:
    access-token:
      expiration-time: 86400000
      secret: changeme
  password:
    strength: 10